# Generated by Django 4.1.4 on 2022-12-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('carmake', models.CharField(max_length=50)),
                ('carmodel', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('insurance', models.CharField(max_length=50)),
                ('rcbook', models.CharField(max_length=50)),
                ('ismanual', models.BooleanField()),
                ('kmsdriven', models.IntegerField()),
                ('numofseats', models.IntegerField()),
                ('ispetrol', models.BooleanField()),
                ('mileage', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
