# Generated by Django 4.1.4 on 2022-12-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateTimeField()),
                ('returndate', models.DateTimeField()),
                ('extratime', models.DateTimeField()),
                ('totalprice', models.IntegerField()),
                ('ismanual', models.BooleanField()),
                ('regid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookings')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='manual_pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('pickupdate', models.DateField()),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookings')),
            ],
            options={
                'db_table': 'manual_pickup',
            },
        ),
    ]
