# Generated by Django 4.1.4 on 2022-12-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bookings_rating_manual_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanceamount', models.IntegerField()),
                ('paymentdate', models.DateTimeField()),
                ('paymenttype', models.CharField(max_length=50)),
                ('totalamount', models.IntegerField()),
                ('remamount', models.IntegerField()),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookings')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='doorstep_pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('deliverydate', models.DateField()),
                ('cost', models.IntegerField()),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookings')),
            ],
            options={
                'db_table': 'doorstep_pickup',
            },
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintmessage', models.CharField(max_length=250)),
                ('complaintdate', models.DateField()),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookings')),
                ('fromuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to='api.user')),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touser', to='api.user')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
    ]
