# Generated by Django 4.1.4 on 2022-12-09 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_payment_doorstep_pickup_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=250)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'license',
            },
        ),
        migrations.CreateModel(
            name='cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelreason', models.CharField(max_length=250)),
                ('canceldate', models.DateField()),
                ('cancellationfee', models.IntegerField()),
                ('refundamount', models.IntegerField()),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookings')),
            ],
            options={
                'db_table': 'cancellation',
            },
        ),
    ]
