# Generated by Django 4.1.4 on 2022-12-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookings',
            new_name='booking',
        ),
    ]
