# Generated by Django 4.1.4 on 2022-12-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_bookings_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='regid',
            new_name='carid',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='regid',
            new_name='carid',
        ),
    ]
