# Generated by Django 4.1.4 on 2022-12-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_regid_booking_carid_rename_regid_car_carid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
    ]
